name: CGL
on:
  push:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        uses: ramsey/composer-install@v3
      - name: Lint
        run: composer lint
      - name: Static analysis
        run: composer sca
